CREATE TABLE IF NOT EXISTS products (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO products (name, price) VALUES
('Laptop', 999.00),
('Mouse', 25.50),
('Keyboard', 45.00)
ON DUPLICATE KEY UPDATE name=VALUES(name), price=VALUES(price);
