---
- name: Find & rsync files from /opt/data to /opt
  hosts: web1
  become: true
  vars:
    search_dir: /opt/data
    dest_dir: /opt

  tasks:
    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: "{{ dest_dir }}"
        state: directory
        mode: '0755'

    - name: Ensure rsync is installed (required by synchronize)
      ansible.builtin.package:
        name: rsync
        state: present

    - name: Find files older than 2 minutes and ≥ 1 MB (recursive)
      ansible.builtin.find:
        paths: "{{ search_dir }}"
        recurse: true
        file_type: file
        age: +2m        # Ouder dan 2 minuten
        size: +1m       # Groter of gelijk aan 1 MB
      register: found

    - name: Rsync matched files to {{ dest_dir }} (preserve attrs)
      ansible.posix.synchronize:
        src: "{{ item.path }}"
        dest: "{{ dest_dir }}/"
        archive: true         # -a (rlptgoD): perms, times, owner, group, etc.
        compress: true        # -z
        rsync_opts:
          - "--checksum"      # verifieer op inhoud
          - "--relative"      # behoudt relatieve padboom
      loop: "{{ found.files }}"
      when: found.matched | default(0) > 0
      delegate_to: "{{ inventory_hostname }}"   # run rsync op de remote (remote→remote)